version: '3.8'

services:
  pay-service-frontend:
    image: moskowpsix/pay-service-frontend:dev
    # Убираем прямой проброс портов - Traefik будет маршрутизировать трафик
    # ports:
    #   - '80:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pay-front-dev.rule=Host(`pay-service-dev.moto.vokrug.city`)"
      - "traefik.http.routers.pay-front-dev.entrypoints=websecure"
      - "traefik.http.routers.pay-front-dev.tls.certresolver=myresolver"
      - "traefik.http.routers.pay-front-dev.service=pay-front-dev-service"
      - "traefik.http.services.pay-front-dev-service.loadbalancer.server.port=80"
      # HTTP router для ACME challenge (без SSL)
      - "traefik.http.routers.pay-front-dev-http.rule=Host(`pay-service-dev.moto.vokrug.city`)"
      - "traefik.http.routers.pay-front-dev-http.entrypoints=web"
      - "traefik.http.routers.pay-front-dev-http.service=pay-front-dev-service"
      - "traefik.http.routers.pay-front-dev-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.docker.network=frontend-network"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 0s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - frontend-network
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  frontend-network:
    driver: overlay
    attachable: true


